/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProdServer;
import Model.ProdutosBEAN;
import Model.XML;
import static Model.XML.arquivoXMLDetCliente;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;

/**
 *
 * @author Gabriel
 */
public class TelaView extends javax.swing.JFrame {

    /**
     * Creates new form TelaView
     */
    public TelaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_consulta = new javax.swing.JTable();
        CBB_CAT_BUSCA = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jIMG = new javax.swing.JLabel();
        EDT_COD = new javax.swing.JTextField();
        EDT_DESC = new javax.swing.JTextField();
        EDT_VENDA = new javax.swing.JTextField();
        EDT_LUCRO = new javax.swing.JTextField();
        EDT_CUSTO = new javax.swing.JTextField();
        EDT_ESTOQUE = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        EDT_UNIDADE = new javax.swing.JTextField();
        EDT_FORNECEDOR = new javax.swing.JTextField();
        EDT_CATEGORIA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setOpaque(true);

        tabela_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_consulta);

        CBB_CAT_BUSCA.setEditable(true);
        CBB_CAT_BUSCA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBB_CAT_BUSCA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GERAL", "AÇOUGUE", "AUTOMOTIVO", "BEBIDAS", "BOLACHA", "DISPOSITIVOS", "ELETRO DOMESTICOS", "HORTIFRUTI", "INFANTIL", "LITERATURA", "PADARIA", "REFRIGERANTES", "UTENCILIOS" }));
        CBB_CAT_BUSCA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CBB_CAT_BUSCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBB_CAT_BUSCAActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setText("PESQUISAR");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("DETALHAR ->");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CBB_CAT_BUSCA, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addGap(200, 200, 200)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CBB_CAT_BUSCA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("TELA DE PESQUISA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel2)
                .addContainerGap(367, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("PESQUISA", jPanel1);

        jIMG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jIMG.setText("IMG");
        jIMG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EDT_COD.setBackground(new java.awt.Color(240, 240, 240));
        EDT_COD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EDT_COD.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "CODIGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        EDT_COD.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        EDT_COD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDT_CODActionPerformed(evt);
            }
        });

        EDT_DESC.setBackground(new java.awt.Color(240, 240, 240));
        EDT_DESC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EDT_DESC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCRIÇÃO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        EDT_DESC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDT_DESCActionPerformed(evt);
            }
        });

        EDT_VENDA.setBackground(new java.awt.Color(240, 240, 240));
        EDT_VENDA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EDT_VENDA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "P. VENDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        EDT_VENDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDT_VENDAActionPerformed(evt);
            }
        });

        EDT_LUCRO.setBackground(new java.awt.Color(240, 240, 240));
        EDT_LUCRO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EDT_LUCRO.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LUCRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        EDT_LUCRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDT_LUCROActionPerformed(evt);
            }
        });

        EDT_CUSTO.setBackground(new java.awt.Color(240, 240, 240));
        EDT_CUSTO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EDT_CUSTO.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "P. CUSTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        EDT_CUSTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDT_CUSTOActionPerformed(evt);
            }
        });

        EDT_ESTOQUE.setBackground(new java.awt.Color(240, 240, 240));
        EDT_ESTOQUE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EDT_ESTOQUE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESTOQUE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        EDT_ESTOQUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDT_ESTOQUEActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setText("<- VOLTAR");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        EDT_UNIDADE.setBackground(new java.awt.Color(240, 240, 240));
        EDT_UNIDADE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EDT_UNIDADE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UNIDADE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        EDT_UNIDADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDT_UNIDADEActionPerformed(evt);
            }
        });

        EDT_FORNECEDOR.setBackground(new java.awt.Color(240, 240, 240));
        EDT_FORNECEDOR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EDT_FORNECEDOR.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORNECEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        EDT_FORNECEDOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDT_FORNECEDORActionPerformed(evt);
            }
        });

        EDT_CATEGORIA.setBackground(new java.awt.Color(240, 240, 240));
        EDT_CATEGORIA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EDT_CATEGORIA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CATEGORIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        EDT_CATEGORIA.setPreferredSize(new java.awt.Dimension(16, 50));
        EDT_CATEGORIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDT_CATEGORIAActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("TELA DE DETALHE DO PRODUTO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EDT_COD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EDT_VENDA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(EDT_LUCRO, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(EDT_CUSTO, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EDT_UNIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EDT_DESC, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(95, 95, 95)))
                        .addComponent(jIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(EDT_CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EDT_ESTOQUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EDT_FORNECEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(690, 690, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EDT_DESC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EDT_COD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EDT_UNIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EDT_CUSTO)
                            .addComponent(EDT_LUCRO, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EDT_VENDA, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EDT_CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EDT_ESTOQUE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EDT_FORNECEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 158, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 355, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("PRODUTO", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Consultar();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void CBB_CAT_BUSCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBB_CAT_BUSCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBB_CAT_BUSCAActionPerformed

    private void EDT_CODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDT_CODActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDT_CODActionPerformed

    private void EDT_DESCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDT_DESCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDT_DESCActionPerformed

    private void EDT_VENDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDT_VENDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDT_VENDAActionPerformed

    private void EDT_LUCROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDT_LUCROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDT_LUCROActionPerformed

    private void EDT_CUSTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDT_CUSTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDT_CUSTOActionPerformed

    private void EDT_ESTOQUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDT_ESTOQUEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDT_ESTOQUEActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.jTabbedPane1.setSelectedIndex(0);
        this.EDT_VENDA.setEnabled(false);
        this.CBB_CAT_BUSCA.requestFocus();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         URL url = null;
        try {
            url = new URL("http://127.0.0.1:9870/Controller?wsdl");
        } catch (MalformedURLException ex) {
            Logger.getLogger(TelaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        QName qname = new QName("http://Controller/", "ProdServerImplService");
        Service ws = Service.create(url, qname);
        ProdServer cone = ws.getPort(ProdServer.class);

        if (tabela_consulta.getRowCount() >= 1) {

            String n = (String) tabela_consulta.getModel().getValueAt(tabela_consulta.getSelectedRow(), 0);

            XML xml = new XML();

            ProdutosBEAN prod = arquivoXMLDetCliente(cone.ProdutosDet((n), "XH58_k+EmDhZdnC"));

            EDT_COD.setText(prod.getCodBarras());
            EDT_DESC.setText(prod.getDescricao());
            EDT_VENDA.setText(Double.toString(prod.getPrecoVenda()));
            EDT_CUSTO.setText(Double.toString(prod.getCusto()));
            
            String Valores;
            Valores = "QTD ATUAL: " + Integer.toString(prod.getEstoqueAtual())+ 
                      " MAXIMO: "+Integer.toString(prod.getEstoqueMaximo())+
                      " MINIMO: "+Integer.toString(prod.getEstoqueMinimos());
            
            EDT_ESTOQUE.setText(Valores);
            
            EDT_CATEGORIA.setText(prod.getCategorias());
            EDT_UNIDADE.setText(prod.getUnidadeMedida());
            EDT_FORNECEDOR.setText(prod.getFornecedores());
                   
            //String caminho = "img\\"+prod.getCategorias()+".png";
            Icon icon = new ImageIcon(prod.getUrl());
            jIMG.setIcon(icon);

            this.jTabbedPane1.setSelectedIndex(1);
            this.EDT_COD.requestFocus();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void EDT_UNIDADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDT_UNIDADEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDT_UNIDADEActionPerformed

    private void EDT_FORNECEDORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDT_FORNECEDORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDT_FORNECEDORActionPerformed

    private void EDT_CATEGORIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDT_CATEGORIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDT_CATEGORIAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBB_CAT_BUSCA;
    private javax.swing.JTextField EDT_CATEGORIA;
    private javax.swing.JTextField EDT_COD;
    private javax.swing.JTextField EDT_CUSTO;
    private javax.swing.JTextField EDT_DESC;
    private javax.swing.JTextField EDT_ESTOQUE;
    private javax.swing.JTextField EDT_FORNECEDOR;
    private javax.swing.JTextField EDT_LUCRO;
    private javax.swing.JTextField EDT_UNIDADE;
    private javax.swing.JTextField EDT_VENDA;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jIMG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabela_consulta;
    // End of variables declaration//GEN-END:variables

    private void Consultar(){
        DefaultTableModel dtmPrincipal = (DefaultTableModel) tabela_consulta.getModel();

        URL url = null;
        try {
            url = new URL("http://127.0.0.1:9870/Controller?wsdl");
        } catch (MalformedURLException ex) {
            Logger.getLogger(TelaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        QName qname = new QName("http://Controller/", "ProdServerImplService");
        Service ws = Service.create(url, qname);
        ProdServer cone = ws.getPort(ProdServer.class);

        File prod = null;
        
        String teste = String.valueOf( CBB_CAT_BUSCA.getSelectedItem());
        if (CBB_CAT_BUSCA.getSelectedIndex() == 0) {
            prod = cone.ListarProdutosAll("XH58_k+EmDhZdnC");
        } else {
            prod = cone.ListarProdutosCategoria(String.valueOf( CBB_CAT_BUSCA.getSelectedItem()), "XH58_k+EmDhZdnC");
        }

        ArrayList<ProdutosBEAN> lista = XML.arquivoXMLCliente(prod);

        dtmPrincipal.setNumRows(0);

        for (int i = 0; i < lista.size(); i++) {
            Object[] linha = {
                lista.get(i).getCodBarras(),
                lista.get(i).getDescricao(),
                lista.get(i).getPrecoVenda()};
            dtmPrincipal.addRow(linha);
        }
    }

}
